# Utilise l'image officielle Python comme image de base
FROM python:3.9

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie les fichiers requis (y compris le fichier Python et les éventuels fichiers de dépendances) dans le conteneur
COPY Commentaires/commentaires.py ./

# Installe les dépendances Python

RUN pip install flask
RUN pip install flask_sqlalchemy
RUN pip install flask_cors
RUN pip install psycopg2
RUN pip install flask_migrate

# Expose le port sur lequel l'application Flask va écouter
EXPOSE 5000

ENV HOST = 0.0.0.0
# Commande pour lancer l'application Flask
CMD ["python", "commentaires.py"]
